name: whatsapp_analyzer

services:
  api:
    build: ./backend
    volumes:
      - server:/whatsapp-analyzer-backend
      - ~/.ssh:/root/.ssh
    ports:
      - 8000:8000
    healthcheck:
      test: curl --fail http://localhost:8000/docs || exit 1
    networks:
      - my_network
    entrypoint: bash clone_and_run.sh

  metrics:
    build: ./generic_repo
    volumes:
      - metrics:/whatsapp-analyzer-metrics
      - ~/.ssh:/root/.ssh
      - ~/.config/nvim:/root/.config/nvim
      - ~/.zshrc:/root/.zshrc
    environment:
      - GITHUB_REPO=git@github.com:JuanJouglard/whatsapp-analyzer-metrics.git
      - FOLDER=whatsapp-analyzer-metrics
    ports:
      - 8004:8004
    healthcheck:
      test: curl --fail http://localhost:8004/docs || exit 1
    networks:
      - my_network
    entrypoint: bash clone_and_run.sh


  frontend:
    build: ./analyzer_frontend
    volumes:
      - analyzer_frontend:/whatsapp-analyzer-frontend
      - ~/.ssh:/root/.ssh
    ports:
      - 5173:5173
    networks:
      - my_network
    entrypoint: bash clone_and_run.sh
    healthcheck:
      test: curl --fail http://localhost:5173/ || exit 1
      disable: true
      interval: 30s
      retries: 0
      start_period: 0s

  s3:
    image: minio/minio
    volumes:
      - s3_buckets:/s3_buckets
    ports:
      - 9000:9000
      - 9001:9001
    command: server /s3_buckets --console-address ":9001"
    networks:
      - my_network

  gateway:
    build: ./gateway
    networks:
      - my_network
    volumes:
      - s3_buckets:/root/s3_buckets
      - server:/root/server
      - analyzer_frontend:/root/analyzer_frontend
      - ml:/root/ml
      - ~/.config/nvim:/root/.config/nvim
      - ~/.oh_my_zsh:/root/.oh_my_zsh
      - ~/.zshrc:/root/.zshrc
      - ~/.ssh:/root/.ssh
    command: tail -f /dev/null

  ml:
    build: ./ml
    entrypoint: bash clone_and_run.sh
    healthcheck:
      test: curl --fail http://localhost:8000/docs || exit 1
    volumes:
      - ml:/whatsapp-ml-service
      - ~/.ssh:/root/.ssh
      - ~/.config/nvim:/root/.config/nvim
      - ~/.zshrc:/root/.zshrc
    ports:
      - 8003:8000
    networks:
      - my_network


networks:
  my_network:

volumes:
  s3_buckets:
  server:
  analyzer_frontend:
  ml:
  metrics:
