name: whatsapp_analyzer

services:
  api:
    build: ./backend
    volumes:
      - server:/server
    ports:
      - 8000:8000
    healthcheck:
      disable: true
      test: curl --fail http://localhost:8000/docs || exit 1
    networks:
      - my_network

  frontend:
    build: ./analyzer_frontend
    volumes:
      - analyzer_frontend:/whatsapp-analyzer-frontend
      - ~/.ssh:/root/.ssh
    ports:
      - 3000:3000
    networks:
      - my_network
    command: /clone_and_run.sh
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      disable: true
      interval: 30s
      retries: 0
      start_period: 0s


  gateway:
    build: ./gateway
    volumes:
      - s3_buckets:/root/s3_buckets
      - server:/root/server
      - analyzer_frontend:/root/analyzer_frontend
      - ml:/root/ml
      - ~/.config/nvim:/root/.config/nvim
      - ~/.oh_my_zsh:/root/.oh_my_zsh
      - ~/.zshrc:/root/.zshrc
      - ~/.ssh:/root/.ssh
    command: tail -f /dev/null

  aws:
    build: ./aws
    environment:
      - SERVICES=s3
    ports:
      - 4566:4566
      - 4572:4572
    volumes:
      - aws:/aws
    profiles: [aws]
    command: /setup_s3.sh


networks:
  my_network:
    driver: bridge

volumes:
  s3_buckets:
  server:
  analyzer_frontend:
  ml:
  aws:
