name: whatsapp_analyzer

services:
  api:
    build: ./backend
    volumes:
      - server:/server
    ports:
      - 8000:8000
    healthcheck:
      disable: true
      test: curl --fail http://localhost:8000/docs || exit 1
    networks:
      - my_network

  frontend:
    build: ./analyzer_frontend
    volumes:
      - analyzer_frontend:/analyzer_frontend
    ports:
      - 3000:3000
    networks:
      - my_network
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      disable: true
      interval: 30s
      retries: 0
      start_period: 0s

  s3:
    image: minio/minio
    volumes:
      - s3_buckets:/s3_buckets
    ports:
      - 9000:9000
      - 9001:9001
    command: server /s3_buckets --console-address ":9001"
    networks:
      - my_network

  gateway:
    build: ./gateway
    volumes:
      - s3_buckets:/root/s3_buckets
      - server:/root/server
      - analyzer_frontend:/root/analyzer_frontend
      - ~/.config/nvim:/root/.config/nvim
      - ~/.oh_my_zsh:/root/.oh_my_zsh
      - ~/.zshrc:/root/.zshrc
    command: tail -f /dev/null
    depends_on:
      - api
      - frontend
      - s3

      #ml:
      #  build:
      #    dockerfile: ./ml/Dockerfile
      #analyzer:
      #  container_name: analyzer_service
      #  ports:
      #    - 4000:4000
      #  networks:
      #    - my_network
      #

networks:
  my_network:
    driver: bridge

volumes:
  s3_buckets:
  server:
  analyzer_frontend:
